# Generated by Django 4.0.3 on 2022-10-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('envs', models.JSONField()),
                ('command', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField()),
                ('params', models.JSONField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='app.app')),
            ],
        ),
    ]
