# Generated by Django 4.1.2 on 2022-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="container",
            name="params",
        ),
        migrations.AddField(
            model_name="container",
            name="command",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="container",
            name="container_id",
            field=models.CharField(default="running", max_length=256),
        ),
        migrations.AddField(
            model_name="container",
            name="envs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="image",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="container",
            name="name",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="container",
            name="state",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
